# Generated by Django 5.2.7 on 2025-11-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Lưu nháp"),
                    ("SUBMITTED", "Đã nộp"),
                    ("LATE", "Nộp muộn"),
                    ("GRADED", "Đã chấm"),
                    ("RETURNED", "Đã trả bài"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="submissions/"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
