# Generated by Django 5.2.7 on 2025-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_quizsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link Zoom/Google Meet",
                max_length=500,
            ),
        ),
    ]
